export const chords = [
  { label: 'A Major', value: 'A', shape: ['x', '0', '2', '2', '2', '0'] },
  { label: 'A Minor', value: 'Am', shape: ['x', '0', '2', '2', '1', '0'] },
  { label: 'A# Major', value: 'A#', shape: ['1', '3', '3', '3', '1', '1'] },
  { label: 'A# Minor', value: 'A#m', shape: ['1', '3', '3', '2', '1', '1'] },
  { label: 'B Major', value: 'B', shape: ['x', '2', '4', '4', '4', '2'] },
  { label: 'B Minor', value: 'Bm', shape: ['x', '2', '4', '4', '3', '2'] },
  { label: 'C Major', value: 'C', shape: ['x', '3', '2', '0', '1', '0'] },
  { label: 'C Minor', value: 'Cm', shape: ['x', '3', '5', '5', '4', '3'] },
  { label: 'C# Major', value: 'C#', shape: ['x', '4', '6', '6', '6', '4'] },
  { label: 'C# Minor', value: 'C#m', shape: ['x', '4', '6', '6', '5', '4'] },
  { label: 'D Major', value: 'D', shape: ['x', 'x', '0', '2', '3', '2'] },
  { label: 'D Minor', value: 'Dm', shape: ['x', 'x', '0', '2', '3', '1'] },
  { label: 'D# Major', value: 'D#', shape: ['x', 'x', '1', '3', '4', '3'] },
  { label: 'D# Minor', value: 'D#m', shape: ['x', 'x', '1', '3', '4', '2'] },
  { label: 'E Major', value: 'E', shape: ['0', '2', '2', '1', '0', '0'] },
  { label: 'E Minor', value: 'Em', shape: ['0', '2', '2', '0', '0', '0'] },
  { label: 'F Major', value: 'F', shape: ['1', '3', '3', '2', '1', '1'] },
  { label: 'F Minor', value: 'Fm', shape: ['1', '3', '3', '1', '1', '1'] },
  { label: 'F# Major', value: 'F#', shape: ['2', '4', '4', '3', '2', '2'] },
  { label: 'F# Minor', value: 'F#m', shape: ['2', '4', '4', '2', '2', '2'] },
  { label: 'G Major', value: 'G', shape: ['3', '2', '0', '0', '0', '3'] },
  { label: 'G Minor', value: 'Gm', shape: ['3', '2', '0', '0', '0', '3'] },
]
